
import React, { useState, useRef, useEffect } from 'react';
import { UserProfile } from '../types';
import { chatWithCoach } from '../services/geminiService';
import { Send, Bot, Mic, X, Download, Table, Sparkles } from 'lucide-react';
import { GoogleGenAI, Modality, LiveServerMessage } from '@google/genai';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

interface Props {
  profile: UserProfile;
  initialPrompt?: string;
  onPromptHandled?: () => void;
}

interface PlanData {
  title: string;
  type: 'diet' | 'workout';
  rows: { col1: string; col2: string; col3: string }[];
  summary: string;
}

const AICoachView: React.FC<Props> = ({ profile, initialPrompt, onPromptHandled }) => {
  const [messages, setMessages] = useState<{role: 'user' | 'titan', text: string, plan?: PlanData}[]>([
    { role: 'titan', text: profile.language === 'pt' ? `Bem-vindo de volta, ${profile.name}. Como posso otimizar seus resultados hoje? Peça-me uma dieta ou treino específico!` : `Welcome back, ${profile.name}. How can I optimize your results today? Ask me for a specific diet or workout!` }
  ]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [isLiveMode, setIsLiveMode] = useState(false);
  const [isLiveActive, setIsLiveActive] = useState(false);
  const endRef = useRef<HTMLDivElement>(null);
  
  const audioContextRef = useRef<AudioContext | null>(null);
  const sessionRef = useRef<any>(null);

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isTyping, isLiveMode]);

  // Handle Initial Prompt (e.g., from Nutrition or Workout tab)
  useEffect(() => {
    if (initialPrompt) {
      handleAutoSend(initialPrompt);
      if (onPromptHandled) onPromptHandled();
    }
  }, [initialPrompt]);

  const handleAutoSend = async (msg: string) => {
    setMessages(prev => [...prev, { role: 'user', text: msg }]);
    processMessage(msg);
  };

  const handleSend = async () => {
    if (!input.trim() || isTyping) return;
    const userMsg = input;
    setInput('');
    setMessages(prev => [...prev, { role: 'user', text: userMsg }]);
    processMessage(userMsg);
  };

  const processMessage = async (msg: string) => {
    setIsTyping(true);
    try {
      const responseText = await chatWithCoach(msg, profile);
      let plan: PlanData | undefined;
      let cleanText = responseText;
      const jsonMatch = responseText.match(/\{[\s\S]*"planData"[\s\S]*\}/);
      if (jsonMatch) {
        try {
          const parsed = JSON.parse(jsonMatch[0]);
          plan = parsed.planData;
          cleanText = responseText.replace(jsonMatch[0], '').trim();
        } catch (e) {
          console.error("Failed to parse plan JSON", e);
        }
      }
      setMessages(prev => [...prev, { role: 'titan', text: cleanText || (profile.language === 'pt' ? "Aqui está o seu plano:" : "Here is your plan:"), plan }]);
    } catch (e) {
      setMessages(prev => [...prev, { role: 'titan', text: profile.language === 'pt' ? "Falha na conexão. Vamos tentar de novo." : "Connection drop. Let's try that again." }]);
    } finally {
      setIsTyping(false);
    }
  };

  const downloadPDF = (plan: PlanData) => {
    const doc = new jsPDF() as any;
    const isPt = profile.language === 'pt';
    doc.setFontSize(22);
    doc.setTextColor(16, 185, 129);
    doc.text(plan.title.toUpperCase(), 14, 22);
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`${isPt ? 'Gerado por TitanFit para' : 'Generated by TitanFit for'} ${profile.name.toUpperCase()}`, 14, 30);
    const headers = plan.type === 'diet' 
      ? [[isPt ? 'Hora' : 'Time', isPt ? 'Refeição' : 'Meal', isPt ? 'Macros/Detalhes' : 'Macros/Details']]
      : [[isPt ? 'Exercício' : 'Exercise', isPt ? 'Séries/Reps' : 'Sets/Reps', isPt ? 'Detalhes' : 'Details']];
    const body = plan.rows.map(row => [row.col1, row.col2, row.col3]);
    doc.autoTable({
      startY: 35,
      head: headers,
      body: body,
      theme: 'grid',
      headStyles: { fillColor: [16, 185, 129], textColor: [255, 255, 255], fontStyle: 'bold' },
      styles: { fontSize: 10, cellPadding: 5 }
    });
    const finalY = (doc as any).lastAutoTable.cursor.y;
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.text(plan.summary, 14, finalY + 15, { maxWidth: 180 });
    doc.save(`${plan.title.replace(/\s+/g, '_')}.pdf`);
  };

  const renderPlan = (plan: PlanData) => {
    const isPt = profile.language === 'pt';
    return (
      <div className="mt-4 bg-slate-900/90 border border-emerald-500/30 rounded-[2rem] overflow-hidden shadow-2xl animate-in zoom-in-95 duration-500">
        <div className="bg-emerald-500/10 p-4 border-b border-emerald-500/20 flex justify-between items-center">
          <div className="flex items-center gap-2 text-emerald-400">
            <Table size={18} />
            <span className="font-black text-[10px] uppercase tracking-widest">{plan.title}</span>
          </div>
          <button onClick={() => downloadPDF(plan)} className="p-2 bg-emerald-500 text-white rounded-xl hover:bg-emerald-400 transition-all flex items-center gap-2 text-[9px] font-black uppercase tracking-widest">
            <Download size={14} />
            {isPt ? 'PDF' : 'DOWNLOAD'}
          </button>
        </div>
        <div className="p-4 overflow-x-auto">
          <table className="w-full text-left text-[11px] border-collapse">
            <thead>
              <tr className="text-slate-500 uppercase font-black tracking-widest border-b border-white/5">
                <th className="pb-3 pr-2">{plan.type === 'diet' ? (isPt ? 'HORA' : 'TIME') : (isPt ? 'EXERCÍCIO' : 'EXERCISE')}</th>
                <th className="pb-3 pr-2">{plan.type === 'diet' ? (isPt ? 'REFEIÇÃO' : 'MEAL') : (isPt ? 'SÉRIES' : 'SETS')}</th>
                <th className="pb-3">{plan.type === 'diet' ? 'MACROS' : (isPt ? 'DETALHE' : 'DETAIL')}</th>
              </tr>
            </thead>
            <tbody className="text-slate-200">
              {plan.rows.map((row, i) => (
                <tr key={i} className="border-b border-white/5">
                  <td className="py-3 pr-2 font-black text-emerald-400">{row.col1}</td>
                  <td className="py-3 pr-2 font-bold">{row.col2}</td>
                  <td className="py-3 text-slate-400">{row.col3}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <div className="mt-4 p-4 bg-emerald-500/5 rounded-2xl border border-emerald-500/10">
            <p className="text-[10px] text-slate-400 leading-relaxed font-medium italic">{plan.summary}</p>
          </div>
        </div>
      </div>
    );
  };

  const startLiveMode = async () => {
    setIsLiveMode(true);
    setIsLiveActive(true);
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    function decode(base64: string) {
      const binaryString = atob(base64);
      const len = binaryString.length;
      const bytes = new Uint8Array(len);
      for (let i = 0; i < len; i++) bytes[i] = binaryString.charCodeAt(i);
      return bytes;
    }

    async function decodeAudioData(data: Uint8Array, ctx: AudioContext, sampleRate: number, numChannels: number): Promise<AudioBuffer> {
      const dataInt16 = new Int16Array(data.buffer);
      const frameCount = dataInt16.length / numChannels;
      const buffer = ctx.createBuffer(numChannels, frameCount, sampleRate);
      for (let channel = 0; channel < numChannels; channel++) {
        const channelData = buffer.getChannelData(channel);
        for (let i = 0; i < frameCount; i++) channelData[i] = dataInt16[i * numChannels + channel] / 32768.0;
      }
      return buffer;
    }

    function encode(bytes: Uint8Array) {
      let binary = '';
      const len = bytes.byteLength;
      for (let i = 0; i < len; i++) binary += String.fromCharCode(bytes[i]);
      return btoa(binary);
    }

    const outputAudioContext = new (window.AudioContext || (window as any).webkitAudioContext)({sampleRate: 24000});
    const inputAudioContext = new (window.AudioContext || (window as any).webkitAudioContext)({sampleRate: 16000});
    audioContextRef.current = outputAudioContext;
    
    let nextStartTime = 0;
    const sources = new Set<AudioBufferSourceNode>();

    const sessionPromise = ai.live.connect({
      model: 'gemini-2.5-flash-native-audio-preview-09-2025',
      callbacks: {
        onopen: async () => {
          const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
          const source = inputAudioContext.createMediaStreamSource(stream);
          const scriptProcessor = inputAudioContext.createScriptProcessor(4096, 1, 1);
          scriptProcessor.onaudioprocess = (e) => {
            const inputData = e.inputBuffer.getChannelData(0);
            const int16 = new Int16Array(inputData.length);
            for (let i = 0; i < inputData.length; i++) int16[i] = inputData[i] * 32768;
            const pcmBlob = {
              data: encode(new Uint8Array(int16.buffer)),
              mimeType: 'audio/pcm;rate=16000',
            };
            sessionPromise.then(s => s.sendRealtimeInput({ media: pcmBlob }));
          };
          source.connect(scriptProcessor);
          scriptProcessor.connect(inputAudioContext.destination);
        },
        onmessage: async (message: LiveServerMessage) => {
          const audioBase64 = message.serverContent?.modelTurn?.parts[0]?.inlineData?.data;
          if (audioBase64) {
            nextStartTime = Math.max(nextStartTime, outputAudioContext.currentTime);
            const buffer = await decodeAudioData(decode(audioBase64), outputAudioContext, 24000, 1);
            const source = outputAudioContext.createBufferSource();
            source.buffer = buffer;
            source.connect(outputAudioContext.destination);
            source.start(nextStartTime);
            nextStartTime += buffer.duration;
            sources.add(source);
            source.onended = () => sources.delete(source);
          }
          if (message.serverContent?.interrupted) {
            sources.forEach(s => s.stop());
            sources.clear();
            nextStartTime = 0;
          }
        },
        onclose: () => setIsLiveActive(false),
        onerror: () => setIsLiveActive(false),
      },
      config: {
        responseModalities: [Modality.AUDIO],
        speechConfig: { voiceConfig: { prebuiltVoiceConfig: { voiceName: 'Zephyr' } } },
        systemInstruction: `You are Titan, the AI Fitness Coach. Respond in ${profile.language === 'pt' ? 'Portuguese' : 'English'}.`
      }
    });
    sessionRef.current = await sessionPromise;
  };

  const stopLiveMode = () => {
    if (sessionRef.current) sessionRef.current.close();
    setIsLiveMode(false);
    setIsLiveActive(false);
    if (audioContextRef.current) audioContextRef.current.close();
  };

  return (
    <div className="flex flex-col h-[calc(100vh-140px)] animate-in slide-in-from-bottom-4 duration-500">
      <div className="flex-1 overflow-y-auto space-y-4 pb-4 px-2 scroll-smooth">
        {!isLiveMode && (
          <div className="flex justify-center mb-6">
            <button onClick={startLiveMode} className="group relative bg-gradient-to-r from-emerald-600 to-cyan-600 px-6 py-4 rounded-[2rem] font-black text-white shadow-xl hover:scale-105 transition-transform overflow-hidden">
              <div className="flex items-center gap-3 relative z-10">
                <Mic size={24} className="animate-bounce" />
                <span>{profile.language === 'pt' ? 'COACHING POR VOZ' : 'LIVE VOICE COACHING'}</span>
              </div>
            </button>
          </div>
        )}

        {isLiveMode ? (
          <div className="flex flex-col items-center justify-center h-full space-y-12">
            <div className="w-48 h-48 rounded-full bg-emerald-500/10 border-4 border-emerald-500/20 flex items-center justify-center relative">
              <div className="w-40 h-40 rounded-full bg-emerald-500/20 animate-pulse absolute" />
              <Bot size={64} className="text-emerald-500 relative z-10" />
            </div>
            <button onClick={stopLiveMode} className="bg-red-500/20 border border-red-500/50 text-red-500 px-8 py-4 rounded-3xl font-black">{profile.language === 'pt' ? 'ENCERRAR' : 'END SESSION'}</button>
          </div>
        ) : (
          messages.map((m, i) => (
            <div key={i} className={`flex flex-col ${m.role === 'user' ? 'items-end' : 'items-start'}`}>
              <div className={`max-w-[90%] p-5 rounded-[2rem] flex gap-3 ${m.role === 'user' ? 'bg-emerald-600 text-white rounded-br-none' : 'bg-slate-800 text-slate-200 border border-white/5 rounded-bl-none'}`}>
                {m.role === 'titan' && <Bot size={18} className="shrink-0 text-emerald-500 mt-1" />}
                <div className="text-sm leading-relaxed font-medium">{m.text}</div>
              </div>
              {m.plan && <div className="w-full max-w-[95%]">{renderPlan(m.plan)}</div>}
            </div>
          ))
        )}
        
        {isTyping && (
          <div className="flex justify-start">
             <div className="bg-slate-800/50 p-4 rounded-3xl border border-white/5 flex items-center gap-2">
               <div className="flex gap-1"><div className="w-1.5 h-1.5 bg-emerald-500 rounded-full animate-bounce" /><div className="w-1.5 h-1.5 bg-emerald-500 rounded-full animate-bounce delay-100" /><div className="w-1.5 h-1.5 bg-emerald-500 rounded-full animate-bounce delay-200" /></div>
             </div>
          </div>
        )}
        <div ref={endRef} />
      </div>

      {!isLiveMode && (
        <div className="sticky bottom-0 bg-slate-900/80 backdrop-blur-md pt-2 pb-2">
          <div className="flex items-center gap-2 bg-slate-800/80 p-2 rounded-2xl border border-white/5 focus-within:border-emerald-500/50 transition-all">
            <input type="text" value={input} onChange={(e) => setInput(e.target.value)} onKeyPress={(e) => e.key === 'Enter' && handleSend()} placeholder={profile.language === 'pt' ? 'Peça um plano...' : 'Ask for a plan...'} className="flex-1 bg-transparent border-none focus:outline-none text-sm px-3 py-2 text-white font-medium" />
            <button onClick={handleSend} disabled={!input.trim() || isTyping} className="bg-emerald-600 p-2.5 rounded-xl text-white disabled:opacity-30 active:scale-90 transition-all"><Send size={18} /></button>
          </div>
        </div>
      )}
    </div>
  );
};

export default AICoachView;
